(function(g){var window=this;'use strict';var uE=function(S){S.publish("cardstatechange",S.ri()&&S.gR()?1:0)},e9=function(S,b){var C=g.LN(b),z=C?b:arguments;
for(C=C?0:1;C<z.length;C++){if(S==null)return;S=S[z[C]]}return S},R9x=function(S){var b=g.MZ(S);
S=g.hi(S);return new g.Ox(b.x,b.y,S.width,S.height)},W88=function(S,b,C){var z=z===void 0?{}:z;
var U;return U=g.kC(S,b,function(){g.ua(U);C.apply(S,arguments)},z)},mS=function(S){S=g.Cx(S);
delete G_[S];g.Z1(G_)&&fM&&fM.stop()},jFM=function(){fM||(fM=new g.M8(function(){lic()},20));
var S=fM;S.isActive()||S.start()},lic=function(){var S=g.$L();
g.vc(G_,function(b){XOK(b,S)});
g.Z1(G_)||jFM()},RY=function(S,b,C,z){g.Bf.call(this);
if(!Array.isArray(S)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(S.length!=b.length)throw Error("Start and end points must be the same length");this.K=S;this.T=b;this.duration=C;this.D=z;this.coords=[];this.progress=this.B=0;this.C=null},XOK=function(S,b){b<S.startTime&&(S.endTime=b+S.endTime-S.startTime,S.startTime=b);
S.progress=(b-S.startTime)/(S.endTime-S.startTime);S.progress>1&&(S.progress=1);S.B=1E3/(b-S.C);S.C=b;O71(S,S.progress);S.progress==1?(S.J=0,mS(S),S.onFinish(),S.Ki()):S.isPlaying()&&S.y9()},O71=function(S,b){typeof S.D==="function"&&(b=S.D(b));
S.coords=Array(S.K.length);for(var C=0;C<S.K.length;C++)S.coords[C]=(S.T[C]-S.K[C])*b+S.K[C]},Ap2=function(S,b){g.Z0.call(this,S);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.B;this.state=b.J},WX=function(S,b,C,z,U){RY.call(this,b,C,z,U);
this.element=S},vz6=function(S,b,C,z,U){if(b.length!=2||C.length!=2)throw Error("Start and end points must be 2D");
WX.call(this,S,b,C,z,U)},K8l=function(S){return Math.pow(S,3)},QFl=function(S){return 3*S*S-2*S*S*S},cpx=function(S){g.D.call(this);
this.K=S||window;this.J=[]},lE=function(S){return S.baseUrl||null},j9=function(S,b){return g.OS(g.D5(S,b),function(C){return!!C})},Dc1=function(S,b,C){function z(a8){var S0=a8.hovercardButton;
if(!S0)return null;S0=S0.subscribeButtonRenderer;if(!S0)return null;var Y=a(S0.unsubscribedButtonText),q=a(S0.subscribedButtonText);if(S0.subscribed){var P=a(S0.subscriberCountWithUnsubscribeText);var r=a(S0.subscriberCountText)}else P=a(S0.subscriberCountText),r=a(S0.subscriberCountWithSubscribeText);var QX=null;if(a8.signinEndpoint){QX=e9(a8,"signinEndpoint","webNavigationEndpointData","url");if(!QX){var u6,d8;QX=(d8=g.M((u6=S0.signInEndpoint)==null?void 0:u6.commandMetadata,g.FO))==null?void 0:
d8.url}if(!QX)return null}return Y&&(q||QX)?{subscribed:S0.subscribed,subscribeText:Y,subscribeCount:P,unsubscribeText:q,unsubscribeCount:r,enabled:S0.enabled,signinUrl:QX,classic:a8.useClassicSubscribeButton}:null}
function U(a8){if(a8){var S0=[],Y=a8.videoId;Y&&S0.push("v="+Y);(Y=a8.playlistId)&&S0.push("list="+Y);(a8=a8.startTimeSeconds)&&S0.push("t="+a8);return"/watch?"+S0.join("&")}}
function a(a8){if(!a8)return null;var S0=a8.simpleText;return S0?S0:a8.runs?g.D5(a8.runs,function(Y){return Y.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var J=b.style,H=b.endpoint||{},B=null,x=null,E=!1,d=null,p=null,F=null,T=null,k=!1,e=null,m=null,R=null,X=null,K=null,N=null;if(J==="VIDEO")g.M(H,g.QV)?B=g.M(H,g.QV).url:(N=g.M(H,g.Cw),B=U(N)),x=!1,d=S,b.thumbnailOverlays?(E=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,p=a(E.text),E=E.style==="LIVE"):p=a(b.videoDuration);else if(J==="PLAYLIST")g.M(H,g.QV)?B=g.M(H,g.QV).url:(N=g.M(H,g.Cw),B=U(N)),x=!1,d=S,F=a(b.playlistLength);else if(J===
"CHANNEL"){if(k=e9(H,"browseEndpoint","browseId"))T=k,B="/channel/"+T;x=!1;d="new";(k=!!b.isSubscribe)?e=z(b):m=a(b.subscribersText)}else J==="WEBSITE"?((R=e9(H,"urlEndpoint","url"))&&(B=R),x=!0,d="new",R=b.icon.thumbnails[0].url):J==="CREATOR_MERCHANDISE"&&(b.productPrice&&(X=a(b.productPrice)),b.additionalFeesText&&(K=a(b.additionalFeesText)),(x=e9(H,"urlEndpoint","url"))&&(B=x),x=!0,d="new");S=e9(b,"title","accessibility","accessibilityData","label");var b2=b.endpoint?b.endpoint.clickTrackingParams:
null,I="";if(b.metadata){var $m=a(b.metadata);$m&&(I=$m)}return{id:"element-"+C,type:J,title:a(b.title),metadata:I,callToAction:a(b.callToAction),Kr:b.image,iconUrl:R,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:p,HZ:E,playlistLength:F,channelId:T,subscribeButton:e,subscribersText:m,isSubscribe:k,targetUrl:B||null,xHk:x,sessionData:b2?{itct:b2}:null,tUB:d,Nq:S?S:null,
isPlaceholder:b.isPlaceholder,impressionUrls:j9(b.impressionUrls||[],lE),pSh:j9(b.hovercardShowUrls||[],lE),clickUrls:j9(H.loggingUrls||[],lE),visualElement:g.uu(b.trackingParams),productPrice:X,additionalFeesText:K,watchEndpoint:N||null}},NPL=function(S,b){var C={startMs:Math.floor(Number(S.startMs)),
impressionUrls:j9(S.impressionUrls||[],lE),elements:j9(S.elements||[],function(z,U){return Dc1(b,z,U)})};
S.trackingParams&&(C.visualElement=g.uu(S.trackingParams));return C},nzK=function(S){g.E8.call(this,S);
this.C=this.endscreen=null;this.K={};this.B={};this.D=this.Y=null;this.X=[];this.J=null;this.YQ=!0;this.T=0;S=S.G();this.j=g.Qy(S)||g.DH(S);this.events=new g.ny(this);g.n(this,this.events);this.events.W(this.player,g.JW("creatorendscreen"),this.onCueRangeEnter);this.events.W(this.player,g.yj("creatorendscreen"),this.onCueRangeExit);this.events.W(this.player,"resize",this.MF);this.events.W(window,"focus",this.GLx);this.load();var b=g.IK("STYLE");(g.cP("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.b1(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},gzM=function(S){return S.player.getVideoData().XR?"current":S.j?"new":"current"},XI=function(S){return S.player.G().playerStyle==="creator-endscreen-editor"},Yg2=function(S){var b=S.player.getVideoData(),C=b.videoId;
S.C&&S.C.abort();C={method:"POST",onFinish:function(U){var a=S.C=null;U.status===200&&(U=U.responseText,U.substring(0,3)===")]}"&&(U=U.substring(3),a=JSON.parse(U),a=NPL(a,gzM(S))));Of(S,a)},
urlParams:{v:C},withCredentials:!0};S.j&&(C.urlParams.ptype="embedded");var z=b.Xz;z&&(C.postParams={ad_tracking:z});if(b=g.BoN(b))if(b=g.DN(b),b=g.KF(b))S.C=g.GS(b,C)},Of=function(S,b,C){C=C===void 0?!0:C;
S.player.pR("creatorendscreen");S.Y&&(S.Y.dispose(),S.Y=null,S.D.dispose(),S.D=null);for(var z=g.t(Object.values(S.K)),U=z.next();!U.done;U=z.next())U.value.dispose();S.K={};S.B={};S.X.length>0&&(S.X.forEach(function(H){H.dispose()}),S.X.length=0);
S.J&&(g.o9(S.J,"ytp-ce-element-show"),S.J.setAttribute("aria-hidden","true"));S.T=0;if((S.endscreen=b)&&b.elements){C&&MM8(S);C=[];z=new g.aw(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});C.push(z);S.player.G().K||(S.Y=new g.Z({U:"div",S:"ytp-ce-shadow"}),g.c6(S.player,S.Y.element,4),S.D=new g.iS(S.Y,200));for(z=0;z<b.elements.length;++z){U=b.elements[z];var a=rpx(S,U);if(a){S.K[U.id]=a;S.B[U.id]=U;g.c6(S.player,a.element,4);var J=new g.aw(U.startMs,U.endMs,{id:"ytp-ce-element-"+
U.id,namespace:"creatorendscreen"});C.push(J);Z7O(S,a,U)}else g.vq(new g.ZL("buildEndscreenElement null",U))}S.player.El(C);S.MF()}},MM8=function(S){var b=g.Gy(),C=g.fV();
C&&b&&S.endscreen.visualElement&&g.qw(g.hQ)(void 0,C,b,S.endscreen.visualElement)},rpx=function(S,b){var C=null;
switch(b.type){case "VIDEO":S={U:"div",i_:["ytp-ce-element","ytp-ce-video"],Z:{tabindex:"0","aria-label":b.Nq||"","aria-hidden":"true"},N:[{U:"div",S:"ytp-ce-element-shadow"},{U:"div",S:"ytp-ce-covering-image",Z:AP(b)},{U:"div",S:"ytp-ce-covering-shadow-top"},{U:"a",S:"ytp-ce-covering-overlay",Z:{href:vX(S,b.targetUrl),tabindex:"-1"},N:[{U:"div",i_:["ytp-ce-video-title","ytp-webkit-ellipsis"],Z:{dir:g.pG(b.title||"")},vS:b.title},{U:"div",S:b.HZ?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
vS:b.videoDuration||void 0}]}]};C=new g.Z(S);break;case "PLAYLIST":S={U:"div",i_:["ytp-ce-element","ytp-ce-playlist"],Z:{tabindex:"0","aria-label":b.Nq||"","aria-hidden":"true"},N:[{U:"div",S:"ytp-ce-element-shadow"},{U:"div",S:"ytp-ce-covering-image",Z:AP(b)},{U:"div",S:"ytp-ce-covering-shadow-top"},{U:"a",S:"ytp-ce-covering-overlay",Z:{href:vX(S,b.targetUrl),tabindex:"-1"},N:[{U:"div",i_:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Z:{dir:g.pG(b.title||"")},vS:b.title},{U:"div",S:"ytp-ce-playlist-count",
N:[{U:"div",S:"ytp-ce-playlist-icon"},{U:"div",S:"ytp-ce-playlist-count-text",vS:b.playlistLength||void 0}]}]}]};C=new g.Z(S);break;case "CHANNEL":C={U:"div",i_:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Z:{tabindex:"0","aria-label":b.Nq||"","aria-hidden":"true"},N:[{U:"div",S:"ytp-ce-element-shadow"},{U:"div",S:"ytp-ce-expanding-overlay",N:[{U:"div",S:"ytp-ce-expanding-overlay-hider"},{U:"div",S:"ytp-ce-expanding-overlay-background"},{U:"div",S:"ytp-ce-expanding-overlay-content",
N:[{U:"div",S:"ytp-ce-expanding-overlay-body",N:[{U:"div",S:"ytp-ce-expanding-overlay-body-padding",N:[{U:"a",i_:["ytp-ce-channel-title","ytp-ce-link"],Z:{href:vX(S,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.pG(b.title||"")},vS:b.title},b.subscribeButton?{U:"div",S:"ytp-ce-subscribe-container",N:[{U:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{U:"div",S:"ytp-ce-channel-subscribers-text",vS:b.subscribersText}:"",b.metadata?{U:"div",i_:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],vS:b.metadata}:""]}]}]}]},{U:"div",S:"ytp-ce-expanding-image",Z:AP(b)}]};C=new g.Z(C);var z=g.n9(document,"div","ytp-ce-channel-subscribe",C.element)[0];if(b.subscribeButton&&b.channelId){g.Up(z,"ytp-ce-subscribe-button");if(S.player.G().K){var U=null;var a=b.sessionData.itct}else U="endscreen",a=null;U=new g.hL(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,U,a,S.player,!1);z.appendChild(U.element);S.X.push(U)}break;case "WEBSITE":S={U:"div",i_:["ytp-ce-element","ytp-ce-website"],Z:{tabindex:"0","aria-label":b.Nq||"","aria-hidden":"true"},N:[{U:"div",S:"ytp-ce-element-shadow"},{U:"div",S:"ytp-ce-expanding-overlay",N:[{U:"div",S:"ytp-ce-expanding-overlay-hider"},{U:"div",S:"ytp-ce-expanding-overlay-background"},{U:"div",S:"ytp-ce-expanding-overlay-content",N:[{U:"div",S:"ytp-ce-expanding-overlay-body",N:[{U:"div",
S:"ytp-ce-expanding-overlay-body-padding",N:[{U:"div",S:"ytp-ce-website-title",Z:{dir:g.pG(b.title||"")},vS:b.title},{U:"div",S:"ytp-ce-website-metadata",vS:b.metadata},{U:"a",i_:["ytp-ce-website-goto","ytp-ce-link"],Z:{href:vX(S,b.targetUrl),target:"_blank",tabindex:"-1"},vS:b.callToAction}]}]}]}]},{U:"div",S:"ytp-ce-expanding-image",Z:AP(b)},{U:"div",S:"ytp-ce-expanding-icon",Z:h9L(b.iconUrl)}]};C=new g.Z(S);break;case "CREATOR_MERCHANDISE":C="",b.productPrice&&(C={U:"div",S:"ytp-ce-merchandise-price-container",
N:[{U:"div",S:"ytp-ce-merchandise-price",vS:b.productPrice}]},b.additionalFeesText&&C.N.push({U:"div",S:"ytp-ce-merchandise-additional-fees",vS:b.additionalFeesText})),S={U:"div",i_:["ytp-ce-element","ytp-ce-merchandise"],Z:{tabindex:"0","aria-label":b.Nq||"","aria-hidden":"true"},N:[{U:"div",S:"ytp-ce-element-shadow"},{U:"div",S:"ytp-ce-expanding-overlay",N:[{U:"div",S:"ytp-ce-expanding-overlay-hider"},{U:"div",S:"ytp-ce-expanding-overlay-background"},{U:"div",S:"ytp-ce-expanding-overlay-content",
N:[{U:"div",S:"ytp-ce-expanding-overlay-body",N:[{U:"div",S:"ytp-ce-expanding-overlay-body-padding",N:[{U:"div",S:"ytp-ce-merchandise-title",Z:{dir:g.pG(b.title||"")},vS:b.title},C,{U:"div",S:"ytp-ce-merchandise-metadata",vS:b.metadata},{U:"a",i_:["ytp-ce-merchandise-goto","ytp-ce-link"],Z:{href:vX(S,b.targetUrl),target:"_blank",tabindex:"-1"},vS:b.callToAction}]}]}]}]},{U:"div",S:"ytp-ce-expanding-image",Z:AP(b)},{U:"div",S:"ytp-ce-merchandise-invideo-cta-container",N:[{U:"div",S:"ytp-ce-merchandise-invideo-cta",
vS:b.callToAction||void 0}]}]},C=new g.Z(S)}b.isPlaceholder&&g.Up(C.element,"ytp-ce-placeholder");return C},AP=function(S){if(S.Kr)var b=S.Kr.thumbnails;
return h9L(b?b[b.length-1].url:null)},h9L=function(S){return S?{style:"background-image: url("+S+")"}:{}},Z7O=function(S,b,C){function z(B){B&&(b.listen("blur",function(){B.style.display!="none"&&S.YQ&&B.focus()}),b.W(B,"focus",a),b.W(B,"blur",J))}
function U(B){S.T+=B;S.T>0?(g.Up(b.element,"ytp-ce-force-expand"),KM(S,C.id,!0)):(g.o9(b.element,"ytp-ce-force-expand"),g.o9(b.element,"ytp-ce-element-hover"),KM(S,C.id,!1))}
function a(){U(1)}
function J(){U(-1)}
b.listen("mouseenter",function(){IiK(S,b,C)});
b.listen("mouseleave",function(){wOc(S,b,C)});
S.player.G().K||b.listen("click",function(){g.Up(b.element,"ytp-ce-element-hover")});
b.listen("click",function(B){L8L(S,C,B)});
b.listen("keypress",function(B){L8L(S,C,B)});
b.listen("focus",function(){IiK(S,b,C)});
b.listen("blur",function(){wOc(S,b,C)});
b.listen("touchstart",function(){IiK(S,b,C)});
var H=g.gq("ytp-ce-expanding-overlay-hider",b.element);H&&b.W(H,"touchstart",function(B){B.stopPropagation();g.o9(b.element,"ytp-ce-element-hover");g.o9(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(B){S.YQ=B.keyCode===9&&!B.shiftKey});
z(g.gq("ytp-sb-subscribe",b.element));z(g.gq("ytp-sb-unsubscribe",b.element));b.listen("focus",a);b.listen("blur",J)},L8L=function(S,b,C){if(b.targetUrl&&(!C||C.type!=="keypress"||C.keyCode===13)){for(var z=C.target;z&&!g.$g(z,"ytp-ce-element");){g.$g(z,"subscribe-label")&&qgl(S,b);
if(g.$g(z,"ytp-ce-channel-subscribe"))return;z=z.parentElement||null}if(!z||g.$g(z,"ytp-ce-element-hover")){C.preventDefault();C.stopPropagation();if(z=S.K[b.id])wOc(S,z,b),z.element.blur();if(C.ctrlKey||C.metaKey||b.tUB==="new")qgl(S,b),S.player.sendVideoStatsEngageEvent(17,void 0),S.player.pauseVideo(),C=g.DN(vX(S,b.targetUrl)),C=g.KF(C),g.YV(C,void 0,b.sessionData);else{var U=g.SH(S.player.G())||S.player.getVideoData().XR,a=function(){var J=vX(S,b.targetUrl),H=b.sessionData,B=b.watchEndpoint,x=
g.$q(J);U&&x&&(x.v||x.list)?S.player.R5(x.v,H,x.list,!1,void 0,B||void 0):g.g2(J,H)};
qgl(S,b,function(){S.player.sendVideoStatsEngageEvent(17,a)})}}}},vX=function(S,b){S=S.player.G();
if(b){if(b.startsWith("//"))return S.protocol+":"+b;if(b.startsWith("/"))return g.aG(S)+b}else return"";return b},IiK=function(S,b,C){g.$g(b.element,"ytp-ce-element-hover")||(C.type==="VIDEO"||C.type==="PLAYLIST"?g.Up(b.element,"ytp-ce-element-hover"):S.player.G().K?(new g.M8(function(){g.Up(b.element,"ytp-ce-element-hover")},200)).start():g.Up(b.element,"ytp-ce-element-hover"),Q3(S,C.pSh),KM(S,C.id,!0))},wOc=function(S,b,C){g.o9(b.element,"ytp-ce-element-hover");
g.o9(b.element,"ytp-ce-force-expand");KM(S,C.id,!1)},KM=function(S,b,C){S.Y&&(C?S.D.show():S.D.hide());
for(var z=g.t(Object.keys(S.K)),U=z.next();!U.done;U=z.next())U=U.value,U!==b&&g.yS(S.K[U].element,"ytp-ce-element-shadow-show",C)},Q3=function(S,b,C){function z(){a||(U++,U===b.length&&(J.stop(),C&&C()))}
if(!b||b.length===0||XI(S))C&&C();else{b=Scx(S,b);var U=0,a=!1,J=new g.M8(function(){a=!0;C&&C()},1E3,S);
J.start();for(S=0;S<b.length;S++)g.NR(b[S],z)}},qgl=function(S,b,C){Q3(S,b.clickUrls,C);
(S=g.fV())&&b.xHk&&g.aI(S,b.visualElement)},Scx=function(S,b){var C=S.player.getVideoData().clientPlaybackNonce;
S=S.player.getCurrentTime().toFixed(2);C={CPN:C,AD_CPN:C,MT:S};S=[];for(var z=0;z<b.length;z++)S.push(bIO(b[z],C));return S},bIO=function(S,b){return S.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(C){var z=unescape(C);
z=z.substring(1,z.length-1);return b[z]?escape(b[z]):C})},CJm=function(S){return typeof S==="string"?S:""},cX=function(S,b,C){for(var z in b)if(b[z]===S)return S;
return C},iIx=function(S,b,C,z){this.value=S;
this.target=b;this.showLinkIcon=C;this.J=z},Dl=function(S){return S.value?S.value:null},NY=function(S){if(!S)return null;
var b=g.DN(CJm(S.value));b=g.KF(b);if(!b)return null;var C=cX(S.target,z4l,"current");if(C==null)S=null;else{var z=S.show_link_icon;S=new iIx(b,C,z==="true"||z==="false"?z==="true":!0,S.pause_on_navigation!=null?S.pause_on_navigation:!0)}return S},$G1=function(S,b,C){this.type=S;
this.trigger=b;this.url=C},o12=function(S){if(!S)return null;
var b=cX(S.type,UG5),C=cX(S.trigger,aMO);S=S.url;S=Array.isArray(S)&&S.length?S[0]:S;S=NY(S?S:null);return b?new $G1(b,C,S):null},JS8=function(S,b,C,z,U){this.id=S;
this.type=b;this.style=C;this.data=U;this.action=z||[]},ySX=function(S,b){return g.sl(S.action,b)},HIk=function(S,b){this.context=S;
this.J=b},Bu2=function(S){return S.customMessage?nM("div","iv-card-message",S.customMessage):""},g4=function(S,b){S="background-image: url("+S+");";
var C=[];b&&C.push(b);return{U:"div",S:"iv-card-image",Z:{style:S},N:C}},sCX=function(S){if(!S.metaInfo||S.metaInfo.length===0)return"";
var b=[];S=g.t(S.metaInfo);for(var C=S.next();!C.done;C=S.next())b.push(nM("li","",C.value));return{U:"ul",S:"iv-card-meta-info",N:b}},nM=function(S,b,C){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.pG(C);return{U:S,Z:b,vS:C}},xG2=function(S){if(!S.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],C={};S.fN&&(b.push("iv-card-action-icon"),C.style="background-image: url("+S.fN+");");C.dir=g.pG(S.customMessage);var z=[{U:"span",vS:S.customMessage}];S.showLinkIcon&&(z.push("\u00a0"),z.push({U:"span",S:"iv-card-link-icon"}));return{U:"div",i_:b,Z:C,N:z}},Yl=function(S,b,C,z){if(z){b=g.t(b);
for(var U=b.next();!U.done;U=b.next())S.J(U.value,z,C.id,C.sessionData,C.R3.click,5)}},E12=function(S,b){this.merchant=S;
this.price=b},dGx=function(S){var b;
(b=S)&&!(b=S.length>1?S.charAt(0)==="/"&&S.charAt(1)!=="/":S==="/")&&(b=S.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?S.indexOf("/redirect?")===-1:!1},pn6=function(S,b){return b?b:dGx(S)?"current":"new"},MY=function(S,b){g.D.call(this);
var C=this;this.element=S;this.context=b;this.MH=!1;this.TE=new Map;this.GE=new Map;this.context.V.addEventListener(g.JW("annotations_module"),function(z){(z=C.TE.get(z))&&z.apply(C)});
this.context.V.addEventListener(g.yj("annotations_module"),function(z){(z=C.GE.get(z))&&z.apply(C)})},r4=function(S,b,C,z,U,a,J){S.context.J.listen(b,"click",function(H){S.PW(C,z,U,a||[],J||0,H)});
S.context.J.listen(b,"touchstart",function(){S.MH=!1});
S.context.J.listen(b,"touchmove",function(){S.MH=!0})},FVO=function(S){var b;
return((b=g.M(S,g.QV))==null?0:b.url)?g.M(S,g.QV).url:(S=g.M(S,g.Cw))&&S.videoId?(b="/watch?v="+S.videoId,S.playlistId&&(b+="&list="+S.playlistId),S.index&&(b+="&index="+S.index),S.startTimeSeconds&&(b+="&t="+S.startTimeSeconds),b):null},Zl=function(S,b,C){return{LB:(S.impressionLoggingUrlsV2s||[]).map(function(z){return z.baseUrl||""}),
click:(C.loggingUrls||[]).map(function(z){return z.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(z){return z.baseUrl||""}),
q5:(b.impressionLoggingUrlsV2s||[]).map(function(z){return z.baseUrl||""}),
K2:(b.clickLoggingUrlsV2s||[]).map(function(z){return z.baseUrl||""})}},Tu1=function(S,b,C){MY.call(this,b,C);
var z=this;this.V=S;this.eventId=null;this.eQ=this.UG=this.oT=this.Y=this.isInitialized=!1;this.cards=[];this.EG=this.X=this.BS=this.D=this.Ri=this.J=null;this.YQ=[];this.kQ=this.T=this.Ey=this.zE=null;this.B=0;this.hB=new g.M8(function(){},C.JB.gi?4E3:3E3);
g.n(this,this.hB);this.NH=new g.M8(function(){});
g.n(this,this.NH);this.sG=new HIk(C,function(U,a,J,H,B,x){r4(z,U,a,J,H,B,x)});
this.j=new g.Z({U:"div",S:"iv-drawer",Z:{id:"iv-drawer"},N:[{U:"div",S:"iv-drawer-header",Z:{"aria-role":"heading"},N:[{U:"span",S:"iv-drawer-header-text"},{U:"button",i_:["iv-drawer-close-button","ytp-button"],Z:{"aria-label":"Hide cards",tabindex:"0"}}]},{U:"div",S:"iv-drawer-content"}]});g.n(this,this.j);this.C=this.j.element;this.PS=new g.iS(this.j,330);g.n(this,this.PS);this.KW=g.gq("iv-drawer-header-text",this.C);this.K=g.gq("iv-drawer-content",this.C);this.addCueRange(0,C.videoData.lengthSeconds*
1E3,"",function(){z.oT&&hP(z,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(z.oT=z.Y)&&IY(z)});
this.De=new g.ny(this);g.n(this,this.De);this.V.addEventListener("videodatachange",this.Eb.bind(this))},VyO=function(S,b){b=b.data;
b.autoOpenMs&&S.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){hP(S,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&S.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){IY(S)});
var C=b.headerText;g.i1(S.KW,C);S.X&&S.X.setAttribute("title",C);b.eventId&&(S.eventId=b.eventId);S.zE=g.uu(b.trackingParams);S.T=g.uu(b.closeTrackingParams);S.Ey=g.uu(b.iconTrackingParams)},PJM=function(S,b){var C=b.cardId?b.cardId:"cr:"+S.B,z=S.V.G().experiments.tB("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&z){var U=b.teaser.simpleCardTeaserRenderer,a=b.icon?b.icon.infoCardIconRenderer:null;b={id:C,timestamp:S.B,type:"simple",teaserText:g.FK(U.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,R3:{},rR:null,h7:U.trackingParams?g.uu(U.trackingParams):null,Ey:a&&a.trackingParams?g.uu(a.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
fN:null,title:"",customMessage:"",url:null,onClickCommand:U.onTapCommand||null};w4(S,b)}else{var J;if((J=b.content)==null?0:J.simpleCardContentRenderer){if(!b.cueRanges.length)return;a=(U=b.content)==null?void 0:U.simpleCardContentRenderer;U=b.teaser.simpleCardTeaserRenderer;var H=b.icon?b.icon.infoCardIconRenderer:null;b={id:C,timestamp:S.B,type:"simple",teaserText:g.FK(U.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:LM(S,C,b,a),sponsored:!1,R3:Zl(a,U,a.command),rR:a.trackingParams?g.uu(a.trackingParams):null,h7:U.trackingParams?g.uu(U.trackingParams):null,Ey:H&&H.trackingParams?g.uu(H.trackingParams):null,imageUrl:qY(a.image.thumbnails,290).url,displayDomain:a.displayDomain?g.FK(a.displayDomain):null,showLinkIcon:!!a.showLinkIcon,fN:null,title:a.title?g.FK(a.title):"",customMessage:a.callToAction?g.FK(a.callToAction):"",url:g.M(a.command,g.QV).url?NY({pause_on_navigation:!S.context.videoData.isLivePlayback,
target:"new",value:g.M(a.command,g.QV).url}):null,onClickCommand:null};w4(S,b)}else{var B;if((B=b.content)==null?0:B.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;U=(a=b.content)==null?void 0:a.collaboratorInfoCardContentRenderer;a=b.teaser.simpleCardTeaserRenderer;H=b.icon?b.icon.infoCardIconRenderer:null;b={id:C,timestamp:S.B,type:"collaborator",teaserText:g.FK(a.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:LM(S,C,b,U),sponsored:!1,R3:Zl(U,a,U.endpoint),rR:U.trackingParams?g.uu(U.trackingParams):null,h7:a.trackingParams?g.uu(a.trackingParams):null,Ey:H&&H.trackingParams?g.uu(H.trackingParams):null,channelId:g.M(U.endpoint,g.mu).browseId,customMessage:U.customText?g.FK(U.customText):null,profileImageUrl:qY(U.channelAvatar.thumbnails,290).url,title:U.channelName?g.FK(U.channelName):"",metaInfo:[U.subscriberCountText?g.FK(U.subscriberCountText):""],url:NY({pause_on_navigation:!S.context.videoData.isLivePlayback,
target:"new",value:g.M(U.endpoint,g.mu).canonicalBaseUrl?g.M(U.endpoint,g.mu).canonicalBaseUrl:"/channel/"+g.M(U.endpoint,g.mu).browseId}),onClickCommand:null};w4(S,b)}else{var x;if((x=b.content)==null?0:x.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;U=(H=b.content)==null?void 0:H.playlistInfoCardContentRenderer;a=b.teaser.simpleCardTeaserRenderer;H=b.icon?b.icon.infoCardIconRenderer:null;b={id:C,timestamp:S.B,type:"playlist",teaserText:g.FK(a.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:LM(S,C,b,U),sponsored:!1,R3:Zl(U,a,U.action),rR:U.trackingParams?g.uu(U.trackingParams):null,h7:a.trackingParams?g.uu(a.trackingParams):null,Ey:H&&H.trackingParams?g.uu(H.trackingParams):null,OM:qY(U.playlistThumbnail.thumbnails,258).url,customMessage:U.customMessage?g.FK(U.customMessage):null,playlistVideoCount:g.FK(U.playlistVideoCount),title:U.playlistTitle?g.FK(U.playlistTitle):"",metaInfo:[U.channelName?g.FK(U.channelName):
"",U.videoCountText?g.FK(U.videoCountText):""],url:NY({pause_on_navigation:!S.context.videoData.isLivePlayback,target:"new",value:FVO(U.action)}),onClickCommand:null};w4(S,b)}else{var E;if((E=b.content)==null?0:E.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var d;U=(d=b.content)==null?void 0:d.videoInfoCardContentRenderer;a=b.teaser.simpleCardTeaserRenderer;H=b.icon?b.icon.infoCardIconRenderer:null;b={id:C,timestamp:S.B,type:"video",teaserText:g.FK(a.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:LM(S,C,b,U),sponsored:!1,R3:Zl(U,a,U.action),rR:U.trackingParams?g.uu(U.trackingParams):null,h7:a.trackingParams?g.uu(a.trackingParams):null,Ey:H&&H.trackingParams?g.uu(H.trackingParams):null,OM:qY(U.videoThumbnail.thumbnails,258).url,videoDuration:U.lengthString?g.FK(U.lengthString):null,customMessage:U.customMessage?g.FK(U.customMessage):null,title:U.videoTitle?g.FK(U.videoTitle):"",metaInfo:[U.channelName?g.FK(U.channelName):
"",U.viewCountText?g.FK(U.viewCountText):""],isLiveNow:!!U.badge,url:NY({pause_on_navigation:!S.context.videoData.isLivePlayback,target:"new",value:FVO(U.action)}),onClickCommand:null};w4(S,b)}}}}}S.B++},qY=function(S,b){for(var C=-1,z=-1,U=0;U<S.length;U++){if(S[U].height===b||S[U].width===290)return S[U];
((S[U].height||0)<b||(S[U].width||0)<290)&&(C<0||(S[C].height||0)<(S[U].height||0)||(S[C].width||0)<(S[U].width||0))?C=U:((S[U].height||0)>=b||(S[U].width||0)>=290)&&(z<0||(S[z].height||0)>(S[U].height||0)||(S[z].width||0)>(S[U].width||0))&&(z=U)}return S[z>=0?z:C]},LM=function(S,b,C,z){return{feature:C.feature?C.feature:"cards",
src_vid:S.context.videoData.videoId,annotation_id:b,ei:S.context.videoData.eventId||"",itct:z.trackingParams||""}},k2l=function(S,b){if(b=tyL(S,b))b===S.J&&(S.J=null),S.V.removeCueRange(b.xr.id),g.b1(b.Kw),g.TK(S.cards,b),S.zY(),SL(S)},hP=function(S,b,C){if(!S.Y){S.PS.show();
S.Ri=new g.M8(function(){g.Up(S.context.V.getRootNode(),g.SV.IV_DRAWER_OPEN)},0);
S.Ri.start();S.De.W(S.K,"mousewheel",function(J){S.hB.start();J.preventDefault();J=J||window.event;var H=0;J.type=="MozMousePixelScroll"?H=0==(J.axis==J.HORIZONTAL_AXIS)?J.detail:0:window.opera?H=J.detail:H=J.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?J.wheelDeltaY/-30:J.wheelDeltaY/-1.2:J.wheelDelta/-1.6:J.wheelDeltaY/-3;if(J=H)S.K.scrollTop+=J});
S.Y=!0;var z=g.fV();z&&S.zE&&S.T&&g.$5(z,[S.zE,S.T]);b={TRIGGER_TYPE:b};for(var U=g.t(S.cards),a=U.next();!a.done;a=U.next())a=a.value,a.Si||(a.Si=!0,uLL(S.context.logger,a.xr.R3.LB,b)),z&&g.$5(z,[a.xr.rR]);uE(S.V);C&&(S.D=new g.M8(function(){S.BS=S.X;S.EG.focus()},330),S.D.start())}},IY=function(S){S.Y&&(S.PS.hide(),g.WA(S.De),g.o9(S.context.V.getRootNode(),g.SV.IV_DRAWER_OPEN),S.Y=!1,uE(S.V),S.D&&S.D.stop(),S.D=new g.M8(function(){S.BS&&(S.BS.focus(),S.BS=null)},330),S.D.start())},e4l=function(S){g.a9(S.UB(),
[g.SV.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.c6(S.V,S.C,5);S.E5();S.X=g.gq("ytp-cards-button",S.V.getRootNode());S.EG=g.gq("iv-drawer-close-button",S.C);S.isInitialized=!0},G21=function(S){S.YQ.push(g.UG("iv-teaser-shown",S.aP,S));
S.YQ.push(g.UG("iv-teaser-hidden",S.h6_,S));S.YQ.push(g.UG("iv-teaser-clicked",S.Gt,S));S.eQ=!0},fM1=function(S,b){var C;
return b.onClickCommand&&((C=g.M(b.onClickCommand,g.CVc))==null?void 0:C.targetId)==="engagement-panel-error-corrections"?(S.kQ=b,!0):!1},mGc=function(S,b){S.kQ=b;
var C=S.V.getVideoData();if(!C)return!1;C=g.WK(C);if(C==null?0:C.markersMap)for(var z,U=0;((z=C)==null?void 0:z.markersMap.length)>U;U++){var a=void 0,J=(a=C)==null?void 0:a.markersMap[U];if(J.key==="ERROR_CORRECTION_MARKERS"&&(a=void 0,(J=(a=J.value)==null?void 0:a.markers)&&J.length>0))return z=void 0,b.startMs=((z=g.M(J[0],g.APm))==null?void 0:z.timeRangeStartMillis)||0,S.kQ=null,!0}return!1},w4=function(S,b){if(!fM1(S,b)||mGc(S,b)){var C=R4U(S,b);
if(C){var z={xr:b,Kw:C.element,Si:!1};if(b.onClickCommand)S.V.L("web_infocards_teaser_show_logging_fix")&&(S.eQ||G21(S),k2l(S,b.id),C=S.findLastIndex(z),g.GK(S.cards,C,0,z));else{S.isInitialized||e4l(S);k2l(S,b.id);var U=S.findLastIndex(z);g.GK(S.cards,U,0,z);C.Cx(S.K,U);S.zY()}b.autoOpen?S.addCueRange(b.startMs,0x8000000000000,b.id,function(){S.Y||(S.J=z,SL(S),WV8(S,z),hP(S,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(C=S.context.V.getCurrentTime()*1E3,C<5E3&&C>b.startMs&&lMO(S,z),S.addCueRange(b.startMs,
b.startMs+1,b.id,function(){lMO(S,z)}),SL(S))}}},R4U=function(S,b){switch(b.type){case "simple":S=S.sG;
var C=b.displayDomain?{U:"div",S:"iv-card-image-text",vS:b.displayDomain}:void 0;var z=xG2(b);C={U:"div",i_:["iv-card"],N:[{U:"a",S:"iv-click-target",Z:{href:b.url?Dl(b.url)||"":""},N:[g4(b.imageUrl,C),{U:"div",S:"iv-card-content",N:[nM("h2",void 0,b.title),z]}]}]};C=new g.Z(C);Yl(S,g.Nq("iv-click-target",C.element),b,b.url);b=C;break;case "collaborator":S=S.sG;C={U:"div",i_:["iv-card","iv-card-channel"],N:[{U:"a",i_:["iv-click-target"],Z:{href:Dl(b.url)||"","data-ytid":b.channelId},N:[g4(b.profileImageUrl),
{U:"div",S:"iv-card-content",N:[Bu2(b),{U:"h2",S:"iv-card-primary-link",vS:b.title},sCX(b)]}]}]};C=new g.Z(C);Yl(S,g.Nq("iv-click-target",C.element),b,b.url);b=C;break;case "playlist":S=S.sG;C={U:"div",i_:["iv-card","iv-card-playlist"],N:[{U:"a",S:"iv-click-target",Z:{href:Dl(b.url)||""},N:[g4(b.OM,{U:"div",S:"iv-card-image-overlay",N:[{U:"span",S:"iv-card-playlist-video-count",vS:b.playlistVideoCount}]}),{U:"div",S:"iv-card-content",N:[Bu2(b),nM("h2","iv-card-primary-link",b.title),sCX(b)]}]}]};
C=new g.Z(C);Yl(S,g.Nq("iv-click-target",C.element),b,b.url);b=C;break;case "productListing":S=S.sG;var U=b.offers.length!=0;C=["iv-card"];z="";var a=xG2(b);U&&(C.push("iv-card-product-listing"),z="iv-card-primary-link",a=b.offers[0],U=[],a.price&&U.push({U:"div",S:"iv-card-offer-price",vS:a.price}),a.merchant&&U.push({U:"div",S:"iv-card-offer-merchant",vS:a.merchant}),a={U:"div",N:U});U=b.url?Dl(b.url)||"":"";C={U:"div",i_:C,Z:{tabindex:"0"},N:[{U:"a",i_:["iv-card-image","iv-click-target"],Z:{style:"background-image: url("+
b.imageUrl+");",href:U,"aria-hidden":"true",tabindex:"-1"}},{U:"div",S:"iv-card-content",N:[b.sponsored?{U:"div",S:"iv-card-sponsored",N:["Sponsored",{U:"div",S:"iv-ad-info-container",N:[{U:"div",S:"iv-ad-info",vS:"{{adInfo}}"},{U:"div",S:"iv-ad-info-icon-container",N:[{U:"div",S:"iv-ad-info-icon"},{U:"div",S:"iv-ad-info-callout"}]}]}]}:"",{U:"a",S:"iv-click-target",Z:{href:U},N:[nM("h2",z,b.title),a]}]}]};C=new g.Z(C);z=g.IK("span");g.i1(z,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
C.qp(z,"adInfo");Yl(S,g.Nq("iv-click-target",C.element),b,b.url);b=C;break;case "video":S=S.sG;z=b.videoDuration?{U:"span",S:"iv-card-video-duration",vS:b.videoDuration}:void 0;a=b.isLiveNow?{U:"span",i_:["yt-badge","yt-badge-live"],vS:"LIVE NOW"}:null;U={U:"div",i_:["iv-card","iv-card-video"],N:[{U:"a",S:"iv-click-target",Z:{href:((C=b.url)==null?void 0:Dl(C))||""},N:[g4(b.OM,z),{U:"div",S:"iv-card-content",N:[Bu2(b),nM("h2","iv-card-primary-link",b.title),sCX(b),a]}]}]};C=new g.Z(U);Yl(S,g.Nq("iv-click-target",
C.element),b,b.url);b=C;break;default:return null}return b},jCX=function(S){if(S.J)return S.J.xr.type==="productListing";
if(S.V.L("enable_wn_infocards")){var b;return!((b=S.cards)==null||!b.length)&&g.NP(S.cards,function(C){return C.xr.type==="productListing"})}return g.NP(S.cards,function(C){return C.xr.type==="productListing"})},SL=function(S){g.yS(S.V.getRootNode(),"ytp-cards-shopping-active",jCX(S))},lMO=function(S,b){if(!g.$g(S.V.getRootNode(),"ytp-cards-teaser-shown")){if(S.J!==b){var C=g.fV(),z=S.J?S.J.xr.Ey:S.Ey;
C&&z&&g.Un(C,[z]);S.J=b;SL(S)}if(C=S.isInitialized)C=S.UB().style.display=="none";C||(C=S.context.V.getPlayerState(),z=C===0&&S.context.V.getCurrentTime()===0,C=!(C===1||C===3||z));C||b.xr.teaserDurationMs&&S.V.Xs(!0,{teaserText:b.xr.teaserText,durationMs:b.xr.teaserDurationMs,onClickCommand:b.xr.onClickCommand});S.NH.isActive()||((!S.Y||!S.hB.isActive()&&S.UG)&&WV8(S,b),S.NH.start(910+b.xr.teaserDurationMs))}},WV8=function(S,b){S.j.Yj?(b=new RY([0,
S.K.scrollTop],[0,b.Kw.offsetTop],600,QFl),S.context.Y.listen(b,"animate",function(C){S.K.scrollTop=C.y}),S.context.Y.listen(b,"finish",function(C){S.K.scrollTop=C.y}),b.play()):(S.j.fd(!0),S.K.scrollTop=b.Kw.offsetTop,S.j.fd(!1))},b8=function(S){return S.J&&S.J.xr?S.J.xr:S.cards[0]&&S.cards[0].xr?S.cards[0].xr:null},tyL=function(S,b){return g.sl(S.cards,function(C){return C.xr.id===b})},Cn=function(S,b,C){MY.call(this,S,b);
this.annotation=C;this.isActive=!1},Xn5=function(S){var b=S.annotation.data;
"start_ms"in b&&"end_ms"in b&&S.addCueRange(Number(b.start_ms),Number(b.end_ms),S.annotation.id,function(){S.show()},function(){S.hide()})},i8=function(S,b,C){Cn.call(this,S,b,C);
this.K=null;this.T=!1;this.Y=null;this.C=!1;this.J=this.B=this.D=null},OI2=function(S,b){var C=C===void 0?0:C;
var z=R9x(b).width;g.gX(b,z);C=new vz6(b,[z,b.offsetTop],[z-z-C,b.offsetTop],200,K8l);g.n(S,C);S.context.Y.listen(C,"begin",function(){g.IE(b,!0)});
C.play()},KV2=function(S,b){if(b.channel_name){var C=S.createElement({U:"div",
i_:["iv-branding-context-name"],vS:b.channel_name}),z=S.createElement({U:"div",i_:["iv-branding-context-subscribe"]}),U=b.standalone_subscribe_button_data;U&&(S.J=new g.hL(U.subscribeText,U.subscribeCount,U.unsubscribeText,U.unsubscribeCount,!!U.enabled,!!U.classic,b.channel_id,!!U.subscribed,U.feature,b.session_data.itct,S.context.V,!1),S.J.Cx(z));var a=S.createElement({U:"div",i_:["iv-branding-context-subscribe-caret"]}),J=S.createElement({U:"div",i_:["branding-context-container-inner"]});J.appendChild(a);
J.appendChild(C);J.appendChild(z);g.IE(J,!1);var H=S.createElement({U:"div",i_:["branding-context-container-outer"]});H.appendChild(J);g.KT(H,"right",b.image_width+"px");g.L9(S.UB(),H);S.Y=new g.M8(function(){AS6(S,J,H)},500);
g.n(S,S.Y);S.context.J.listen(S.UB(),"mouseover",function(){v1k(S,J,H,a,b.image_height)});
S.context.J.listen(S.UB(),"mouseout",function(){S.Y.start()})}},v1k=function(S,b,C,z,U){S.Y.stop();
if(!S.C){var a=g.hi(b);S.J||(b.style.width=g.nT(a.width,!0),C.style.width=g.nT(a.width,!0));g.KT(z,"top",a.height-Math.max(Math.min(a.height,U)/2+10,20)+"px");g.KT(z,"right","1px");S.C=!0;g.IE(b,!0);S.D=new g.M8(function(){g.Up(this.UB(),"iv-branding-active")},0,S);
S.D.start()}},AS6=function(S,b,C){g.o9(S.UB(),"iv-branding-active");
S.B=new g.M8(function(){g.IE(b,!1);S.J||(C.style.width=g.nT(0,!0))},250);
S.B.start();S.C=!1},QCU=function(S,b,C,z,U,a,J){this.J=S;
this.Y=b;this.JB=C;this.videoData=z;this.logger=U;this.V=a;this.K=J},cSL=function(S,b,C){Cn.call(this,S,b,C);
var z=this;this.X=this.isCollapsed=this.j=!1;this.B=5E3;this.K=this.Y=this.J=this.C=null;this.T=this.createElement({U:"div",i_:["iv-promo-contents"]});this.D=new g.M8(function(){z.J.setAttribute("aria-hidden","true");g.IE(z.Y,!1);g.IE(z.K,!0)},700,this);
g.n(this,this.D)},Nu5=function(S){var b=S.annotation.data;
if(S.annotation.style==="cta")var C=6;else if(S.annotation.style==="video"||S.annotation.style==="playlist")C=7;S.B=b.collapsedelay_ms||S.B;var z=["iv-promo","iv-promo-inactive"];S.UB().setAttribute("aria-hidden","true");S.UB().setAttribute("aria-label","Promotion");S.UB().tabIndex=0;var U=S.annotation.Hs(),a=b.image_url;if(a){var J=S.createElement({U:"div",i_:["iv-promo-img","iv-click-target"]});a=S.createElement({U:"img",Z:{src:a,"aria-hidden":"true"}});J.appendChild(a);b.video_duration&&!b.is_live?
(a=S.createElement({U:"span",S:"iv-promo-video-duration",vS:b.video_duration}),J.appendChild(a)):b.playlist_length&&(a=S.createElement({U:"span",S:"iv-promo-playlist-length",vS:b.playlist_length.toString()}),J.appendChild(a));U&&r4(S,J,U,S.annotation.id,b.session_data,void 0,C)}U?(a=S.createElement({U:"a",S:"iv-promo-txt"}),g.Y_(a,Dl(U)),S.J=a):S.J=S.createElement({U:"div",S:"iv-promo-txt"});switch(S.annotation.style){case "cta":case "website":var H=S.createElement({U:"p",N:[{U:"strong",vS:b.text_line_1}]});
var B=S.createElement({U:"p",N:[{U:"span",S:"iv-promo-link",vS:b.text_line_2}]});if(a=b.text_line_3){z.push("iv-promo-website-card-cta-redesign");var x=S.createElement({U:"button",i_:["iv-promo-round-expand-icon","ytp-button"]});a=S.createElement({U:"button",i_:["iv-button","iv-promo-button"],N:[{U:"span",S:"iv-button-content",vS:a}]});var E=S.createElement({U:"div",S:"iv-promo-button-container"});E.appendChild(a);U&&r4(S,S.UB(),U,S.annotation.id,b.session_data,void 0,C)}g.Up(S.J,"iv-click-target");
U&&r4(S,S.J,U,S.annotation.id,b.session_data,void 0,C);break;case "playlist":case "video":H=S.createElement({U:"p",N:[{U:"span",vS:b.text_line_1}]}),B=S.createElement({U:"p",N:[{U:"strong",vS:b.text_line_2}]}),b.is_live&&(H=B,B=S.createElement({U:"span",i_:["yt-badge","iv-promo-badge-live"],vS:"LIVE NOW"})),g.Up(S.J,"iv-click-target"),U&&r4(S,S.J,U,S.annotation.id,b.session_data,void 0,C),z.push("iv-promo-video")}H&&S.J.appendChild(H);B&&S.J.appendChild(B);S.T.appendChild(S.J);E&&S.T.appendChild(E);
C=S.createElement({U:"div",S:"iv-promo-actions"});S.K=S.createElement({U:"button",i_:["iv-promo-expand","ytp-button"]});S.K.title="Expand";S.context.J.listen(S.K,"click",function(d){DGk(S,5E3,d)});
C.appendChild(S.K);g.IE(S.K,!1);S.context.J.listen(S.UB(),"mouseover",S.sia,S);S.context.J.listen(S.UB(),"mouseout",S.bxh,S);S.context.J.listen(S.UB(),"touchend",function(d){DGk(S,5E3,d)});
S.Y=S.createElement({U:"button",i_:["iv-promo-close","ytp-button"]});S.Y.title="Close";S.context.J.listen(S.Y,"click",S.annotation.style==="cta"&&b.text_line_3?S.dHR:S.kEB,S);C.appendChild(S.Y);g.a9(S.UB(),z);J&&(g.L9(S.UB(),J),x&&J.appendChild(x));g.L9(S.UB(),S.T);g.L9(S.UB(),C)},DGk=function(S,b,C){C.stopPropagation();
n1c(S);g11(S,b);S.J.focus()},Yc1=function(S){S.isCollapsed||S.X||S.C||(g.Up(S.UB(),"iv-promo-collapsed"),S.isCollapsed=!0,S.D.start())},n1c=function(S){S.D.stop();
S.isCollapsed&&(g.J6(S.UB(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),S.isCollapsed=!1,S.J&&S.J.removeAttribute("aria-hidden"),g.IE(S.K,!1),g.IE(S.Y,!0))},g11=function(S,b){S.C||(S.C=g.AB(function(){My6(this);
Yc1(this)},b,S))},My6=function(S){S.C&&(g.Ym.clearTimeout(S.C),S.C=null)},rSX=function(S){this.V=S},uLL=function(S,b,C){b&&(C?zo(S,b.map(function(z){return g.GW(z,C)})):zo(S,b))},zo=function(S,b,C,z){var U=1,a=void 0,J=-1;
if(C){var H=!1;a=function(){U--;U||H||(clearTimeout(J),H=!0,C())};
J=setTimeout(function(){H=!0;C()},1E3)}b=g.t(b||[]);
for(var B=b.next();!B.done;B=b.next())B=B.value,U++,g.NR(B,a);z&&(U++,z!==0&&S.V.sendVideoStatsEngageEvent(z,a))},ZIc=function(S){g.E8.call(this,S);
var b=this;this.YQ=this.X=!1;this.loadNumber=0;this.B={};this.logger=new rSX(this.player);this.C=new g.ny(this);this.D=this.T=null;this.events=new g.ny(this);this.AO=this.j=this.J=null;this.kQ=[];g.n(this,this.C);this.C.W(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.C.W(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.C.W(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.C.W(this.player,"resize",function(z){b.publish("resize",z)});
this.C.W(this.player,"presentingplayerstatechange",function(z){b.publish("presentingplayerstatechange",z)});
this.subscribe("presentingplayerstatechange",this.tM,this);this.subscribe("resize",this.HI,this);this.player.G().BS.subscribe("vast_info_card_add",this.Yc,this);g.n(this,this.events);this.sG=this.createElement({U:"div",S:"video-custom-annotations"});this.K=new g.Z({U:"div",i_:["ytp-player-content","ytp-iv-player-content"]});g.n(this,this.K);g.c6(this.player,this.K.element,4);this.K.hide();this.Y=new g.Z({U:"div",i_:["ytp-iv-video-content"]});g.n(this,this.Y);S=this.createElement({U:"div",S:"video-annotations"});
S.appendChild(this.sG);this.Y.element.appendChild(S);this.X1()&&this.load();var C=this.createElement({U:"style"});(g.cP("HEAD")[0]||document.body).appendChild(C);this.addOnDisposeCallback(function(){g.b1(C)});
if(S=C.sheet)S.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),S.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),S.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),S.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),S.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),S.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),S.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),S.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),S.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),S.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},h42=function(S){S=S.createElement({U:"div",
i_:["annotation","annotation-type-custom"]});g.IE(S,!1);return S},IML=function(S,b){b=!b.isCued()&&!g.h(b,1024);
S.K.fd(b);S.Y.fd(b)},wnL=function(S,b,C){S.X=!0;
S.D=g.GS(b,C)},LVX=function(S,b){for(var C={},z=g.t(b.attributes),U=z.next();!U.done;U=z.next())U=U.value,C[U.name]=U.nodeValue;
for(z=0;z<b.childNodes.length;z++)if(U=b.childNodes[z],g.qC(U)&&U.nodeType==1){if(C[U.tagName])var a=C[U.tagName];else if(U.tagName==="data"){U.childNodes.length>0&&(a=U.childNodes[0].nodeValue,C[U.tagName]=typeof a==="string"?a.trim():a);continue}else a=[],C[U.tagName]=a;U&&U.tagName==="TEXT"?U.childNodes.length===1&&U.childNodes[0].nodeType===3?a.push(U.childNodes[0].nodeValue):a.push(""):U&&a.push(LVX(S,U))}return C},Cf1=function(S){var b=g.c(S.player.getVideoData());
if(b.PS){var C=S.player.G().BS.get(b.videoId);if(C){var z={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(U,a,J){U=S.loadNumber;a=b.videoId;S.loaded&&S.loadNumber===U&&S.player.getVideoData().videoId===a&&(J=g.E4(J)&&J.responseXML?J.responseXML:null)&&qcO(S,J)}};
g.C5()&&(z.onFinish=SiX(S,z.onFinish));z.postParams={ic_only:"1"};bD5(z,C);S.X=!0;g.GS(b.PS,z)}}},bD5=function(S,b){S.method="POST";
S.postParams=S.postParams||{};b.B9&&(S.postParams.ic_coll=b.B9);b.Yt&&(S.postParams.ic_xml=b.Yt);b.FE&&(S.postParams.ic_track=b.FE)},iDk=function(S){var b=new g.Z({U:"div"});
g.IE(b.element,!1);var C=new Tu1(S.player,b.element,$k(S));g.n(C,b);b.Cx(S.K.element);C.Hf();return C},$l2=function(S,b){var C,z;
if(b=(C=b.getWatchNextResponse())==null?void 0:(z=C.cards)==null?void 0:z.cardCollectionRenderer)S.YQ=!0,zj1(S,b),b.headerText&&S.AO&&(C=g.FK(b.headerText),S.AO.setAttribute("title",C))},$k=function(S){if(!S.j){var b=new cpx(S);
g.n(S,b);var C=new g.xE(S);g.n(S,C);S.j=new QCU(b,C,S.player.G(),S.player.getVideoData(),S.logger,S.player,S.eg)}return S.j},qcO=function(S,b){var C=!1,z=b.getElementsByTagName("annotations");
if(z&&!(z.length<1)&&(z=z[0].getAttribute("itct"))){var U=g.fV();if(U){var a=g.Gy();a&&g.qw(g.ZX)(void 0,U,a,[g.uu(z)])}}b=b.getElementsByTagName("annotation");for(z=0;z<b.length;z++){a=LVX(S,b[z]);U=null;try{if(a){var J=a.id,H=/.+/;var B=typeof J==="string"&&H!=null&&J!=null&&J.match(H)?J:"";var x=cX(a.type,Ul5),E=cX(a.style,aFK),d=CJm(a.data),p=d.length!==0?JSON.parse(d):{};var F=a.action;a=o12;if(F==null)var T=null;else if(g.LN(F)){H=[];for(var k=g.t(F),e=k.next();!e.done;e=k.next()){var m=a(e.value);
m&&H.push(m)}T=H}else{var R=a(F);T=R?[R]:[]}U=B&&x?new JS8(B,x,E,T,p):null}else U=null}catch($m){}if(U)if(U.type==="branding"||U.type==="promotion"){a=S;H=U;var X=h42(a),K=null;switch(H.type){case "branding":if(a.player.G().eZ)break;a.K.element.appendChild(X);K=new i8(X,$k(a),H);break;case "promotion":g.c6(a.player,X,4),K=new cSL(X,$k(a),H)}K&&K.Hf();if(a=K)g.n(S,a),S.B[U.id]=a}else if(U.type==="card"||U.type==="drawer"){S.J||(S.J=iDk(S),g.n(S,S.J));if(U.type==="card"){X=S.J;var N=(C=U)&&C.data&&
C.data.card_type;U=C.data;if(N)switch(a=U.tracking||{},a={LB:a.impression,click:a.click,close:a.close,q5:a.teaser_impression,K2:a.teaser_click},H=U.tracking_params||{},K=null,N){case "collaborator":C={id:C.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,R3:a,rR:H.card?g.uu(H.card):null,h7:H.teaser?g.uu(H.teaser):null,Ey:H.icon?g.uu(H.icon):
null,channelId:U.channel_id,customMessage:U.custom_message?U.custom_message:null,profileImageUrl:U.image_url,title:U.title,metaInfo:U.meta_info,url:NY({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url}),onClickCommand:null};w4(X,C);break;case "playlist":C={id:C.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,R3:a,
rR:H.card?g.uu(H.card):null,h7:H.teaser?g.uu(H.teaser):null,Ey:H.icon?g.uu(H.icon):null,OM:U.image_url,playlistVideoCount:U.playlist_video_count,customMessage:U.custom_message?U.custom_message:null,title:U.title,metaInfo:U.meta_info,url:g.c(NY({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url})),onClickCommand:null};w4(X,C);break;case "productListing":U.signin_url&&(K=NY({target:"current",value:U.signin_url}));N=[];for(var b2=U.offers||[],I=0;I<b2.length;I++)N.push(new E12(g.se(b2[I].merchant),
g.se(b2[I].price)));C={id:C.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,R3:a,rR:H.card?g.uu(H.card):null,h7:H.teaser?g.uu(H.teaser):null,Ey:H.icon?g.uu(H.icon):null,imageUrl:U.image_url,displayDomain:U.display_domain?U.display_domain:null,showLinkIcon:!!U.show_link_icon,fN:U.button_icon_url?U.button_icon_url:null,title:U.title,customMessage:U.custom_message?
U.custom_message:null,url:g.c(NY({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url})),enB:K,dwx:U.signin_title?U.signin_title:void 0,kjk:U.signin_message?U.signin_message:void 0,offers:N,onClickCommand:null};w4(X,C);break;case "simple":C={id:C.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,R3:a,rR:H.card?g.uu(H.card):
null,h7:H.teaser?g.uu(H.teaser):null,Ey:H.icon?g.uu(H.icon):null,imageUrl:U.image_url,displayDomain:U.display_domain?U.display_domain:null,showLinkIcon:!!U.show_link_icon,fN:U.button_icon_url?U.button_icon_url:null,title:U.title,customMessage:U.custom_message?U.custom_message:null,url:g.c(NY({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url})),onClickCommand:null};w4(X,C);break;case "video":C={id:C.id,timestamp:U.timestamp||0,type:U.card_type,teaserText:U.teaser_text,teaserDurationMs:U.teaser_duration_ms,
startMs:U.start_ms,autoOpen:U.auto_open||!1,sessionData:U.session_data||{},sponsored:U.sponsored||!1,R3:a,rR:H.card?g.uu(H.card):null,h7:H.teaser?g.uu(H.teaser):null,Ey:H.icon?g.uu(H.icon):null,OM:U.image_url,videoDuration:U.video_duration||null,customMessage:U.custom_message?U.custom_message:null,title:U.title,metaInfo:U.meta_info,isLiveNow:!!U.is_live_now,url:g.c(NY({pause_on_navigation:U.pause_on_navigation,target:U.target||"new",value:U.url})),onClickCommand:null},w4(X,C)}}else VyO(S.J,U);C=!0}}C&&
(uE(S.player),S.HI())},zj1=function(S,b){var C=!1;
S.J||(S.J=iDk(S),g.n(S,S.J));for(var z=g.t(b.cards||[]),U=z.next();!U.done;U=z.next())U=U.value,U.cardRenderer&&(PJM(S.J,U.cardRenderer),C=!0);if(C){var a;(a=S.player.getVideoData())!=null&&g.A9(a)||(C=S.J,z=b.headerText?g.FK(b.headerText):"",g.i1(C.KW,z),C.X&&C.X.setAttribute("title",z),C.context.videoData.eventId&&(C.eventId=C.context.videoData.eventId),C.zE=b.trackingParams?g.uu(b.trackingParams):null,C.T=b.closeButton.infoCardIconRenderer.trackingParams?g.uu(b.closeButton.infoCardIconRenderer.trackingParams):
null,C.Ey=b.icon.infoCardIconRenderer.trackingParams?g.uu(b.icon.infoCardIconRenderer.trackingParams):null,S.HI());uE(S.player)}},oNU=function(S,b,C,z,U){if(!S.player.G().eZ){var a=[];
b.navigationEndpoint&&g.M(b.navigationEndpoint,g.mu)&&g.M(b.navigationEndpoint,g.mu).browseId&&a.push(new $G1("openUrl","click",new iIx("/channel/"+g.M(b.navigationEndpoint,g.mu).browseId,"new",!0,!0)));var J=b.watermark.thumbnails[0];z={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:J.height,image_type:1,image_url:J.url,image_width:J.width,is_mobile:!1,session_data:{annotation_id:C,ei:U,feature:"iv",itct:b.trackingParams,src_vid:z},start_ms:b.startTimeMs};if(b.subscribeButton&&g.M(b.subscribeButton,
g.RR)){z.channel_id=g.M(b.subscribeButton,g.RR).channelId;var H;b=g.M(b.subscribeButton,g.RR);J=U=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(U=g.FK(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(J=g.FK(b.subscriberCountText))):(b.subscriberCountText&&(U=g.FK(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(J=g.FK(b.subscriberCountWithSubscribeText)));var B,x=((B=g.M((H=b.signInEndpoint)==null?void 0:H.commandMetadata,g.FO))==null?void 0:B.url)||"";H={subscribeText:g.FK(b.unsubscribedButtonText),
subscribeCount:U||"",unsubscribeText:g.FK(b.subscribedButtonText),unsubscribeCount:J||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:x};z.standalone_subscribe_button_data=H}a=new JS8(C,"branding","branding",a,z);H=h42(S);S.K.element.appendChild(H);a=new i8(H,$k(S),a);a.Hf();g.n(a,a);S.B[C]=a}},SiX=function(S,b){return function(){var C=g.Az.apply(0,arguments);
S.AB()||S.kQ.push(g.QA.bR(function(){b.apply(null,g.u(C))}))}},JOl=function(S){return S==="annotation-editor"||S==="live-dashboard"};
g.lp.prototype.Xs=g.H2(45,function(S,b){var C=g.R3(this.zl());C&&C.Xs(S,b)});
var G_={},fM=null;g.a5(RY,g.Bf);g.y=RY.prototype;g.y.getDuration=function(){return this.duration};
g.y.play=function(S){if(S||this.J==0)this.progress=0,this.coords=this.K;else if(this.isPlaying())return!1;mS(this);this.startTime=S=g.$L();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.oB();this.EC("play");this.isPaused()&&this.EC("resume");this.J=1;var b=g.Cx(this);b in G_||(G_[b]=this);jFM();XOK(this,S);return!0};
g.y.stop=function(S){mS(this);this.J=0;S&&(this.progress=1);O71(this,this.progress);this.onStop();this.Ki()};
g.y.pause=function(){this.isPlaying()&&(mS(this),this.J=-1,this.EC("pause"))};
g.y.FB=function(){this.J==0||this.stop(!1);this.EC("destroy");RY.I7.FB.call(this)};
g.y.destroy=function(){this.dispose()};
g.y.y9=function(){this.EC("animate")};
g.y.EC=function(S){this.dispatchEvent(new Ap2(S,this))};
g.a5(Ap2,g.Z0);g.a5(WX,RY);WX.prototype.Y=function(){};
WX.prototype.y9=function(){this.Y();WX.I7.y9.call(this)};
WX.prototype.Ki=function(){this.Y();WX.I7.Ki.call(this)};
WX.prototype.oB=function(){this.Y();WX.I7.oB.call(this)};
g.a5(vz6,WX);vz6.prototype.Y=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.V(cpx,g.D);g.y=cpx.prototype;g.y.listen=function(S,b,C,z){C=(0,g.i6)(C,z||this.K);S=g.kC(S,b,C);this.J.push(S);return S};
g.y.Zs=function(S,b,C,z){C=(0,g.i6)(C,z||this.K);S=W88(S,b,C);this.J.push(S);return S};
g.y.ir=function(S){g.ua(S);g.TK(this.J,S)};
g.y.removeAll=function(){g.ua(this.J);this.J.length=0};
g.y.FB=function(){this.removeAll();g.D.prototype.FB.call(this)};g.V(nzK,g.E8);g.y=nzK.prototype;g.y.load=function(){g.E8.prototype.load.call(this);if(!XI(this)){var S=g.slm(this.player.getVideoData());S?(S=NPL(S,gzM(this)),Of(this,S,!1)):Yg2(this)}};
g.y.unload=function(){Of(this,null);this.C&&(this.C.abort(),this.C=null);g.E8.prototype.unload.call(this)};
g.y.Q0=function(S,b){return XI(this)?S==="loadCustomEndscreenRenderer"?(S=NPL(b,"new"),Of(this,S),!0):null:null};
g.y.getOptions=function(){return XI(this)?["loadCustomEndscreenRenderer"]:[]};
g.y.MF=function(){if(this.endscreen&&this.endscreen.elements){var S=this.player.getVideoContentRect();if(S&&S.width!==0&&S.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var C=S.width/S.height;var z=0;for(var U=-1,a=0;a<yOc.length;a++){var J=Math.abs(b.width-yOc[a]);if(U===-1||z>=J)U=a,z=J}z=HDX[U];this.Y&&g.KT(this.Y.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(a=this.endscreen.elements[b].id,U=this.K[a],
J=this.B[a],U&&J){var H=J.width*C/J.aspectRatio,B=Math.round(J.width*S.width);a=Math.round(H*S.height);var x=S.left+Math.round(J.left*S.width),E=S.top+Math.round(J.top*S.height);g.ZU(U.element,B,a);g.gX(U.element,x,E);g.J6(U.element,Bsx);B>256||a>256?g.Up(U.element,"ytp-ce-large-round"):B>96||a>96?g.Up(U.element,"ytp-ce-medium-round"):g.Up(U.element,"ytp-ce-small-round");g.J6(U.element,sx8);B=J.left+J.width/2;J=J.top+H/2;g.Up(U.element,B<=.5&&J<=.5?"ytp-ce-top-left-quad":B>.5&&J<=.5?"ytp-ce-top-right-quad":
B<=.5&&J>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.J6(U.element,HDX);g.Up(U.element,z);(U=g.n9(document,"div","ytp-ce-expanding-overlay-body",U.element)[0])&&g.KT(U,"height",a+"px")}}}}};
g.y.onCueRangeEnter=function(S){if(this.endscreen)if(S.getId()==="ytp-ce-in-endscreen")Q3(this,this.endscreen.impressionUrls),(S=g.fV())&&this.endscreen.visualElement&&g.zD(S,this.endscreen.visualElement),this.J&&(g.Up(this.J,"ytp-ce-element-show"),this.J.removeAttribute("aria-hidden"),this.player.ri()?g.Up(this.J,"ytp-ce-hide-button-lower"):g.o9(this.J,"ytp-ce-hide-button-lower"));else{S=S.getId().substring(15);var b=this.K[S],C=this.B[S];g.Up(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");
b=this.player.getRootNode();g.Up(b,"ytp-ce-shown");Q3(this,C.impressionUrls);(b=g.fV())&&g.zD(b,C.visualElement);this.player.G().T&&this.player.xQ("endscreenelementshown",S)}};
g.y.onCueRangeExit=function(S){if(S.getId()==="ytp-ce-in-endscreen")this.J&&(g.o9(this.J,"ytp-ce-element-show"),this.J.setAttribute("aria-hidden","true"));else{S=S.getId().substring(15);var b=this.K[S];g.o9(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.o9(b,"ytp-ce-shown");this.player.G().T&&this.player.xQ("endscreenelementhidden",S)}};
g.y.GLx=function(S){var b=this;S.target===window&&(new g.M8(function(){for(var C=g.t(Object.values(b.K)),z=C.next();!z.done;z=C.next())g.J6(z.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.y.fd=function(S){for(var b=g.t(Object.values(this.K)),C=b.next();!C.done;C=b.next())C=C.value,S?C.element.setAttribute("hidden",""):C.element.removeAttribute("hidden")};
g.y.vsR=function(S){this.J&&this.player.getRootNode().removeChild(this.J);S&&(g.Up(S,"ytp-ce-hide-button-container"),this.J=S,g.c6(this.player,this.J,4))};
var yOc=[346,426,470,506,570,640,853,1280,1920],HDX="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),sx8=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Bsx=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var z4l={bUx:"current",a3G:"new"};var UG5={CLOSE:"close",Ekx:"openUrl",SUBSCRIBE:"subscribe"},aMO={N1E:"click",CLOSE:"close",owR:"hidden",yix:"rollOut",Pui:"rollOver",Em_:"shown"};JS8.prototype.Hs=function(){var S=ySX(this,function(b){return b.type==="openUrl"&&b.url!=null});
return S?S.url:null};
var aFK={YjS:"anchored",C4:"branding",CHANNEL:"channel",FtB:"cta",zSQ:"highlightText",Y3i:"label",PLAYLIST:"playlist",POPUP:"popup",eZx:"speech",SUBSCRIBE:"subscribe",ilB:"title",VIDEO:"video",qOH:"website"},Ul5={C4:"branding",uCh:"card",A7_:"drawer",Che:"highlight",V9B:"marker",V3R:"promotion",TEXT:"text",myk:"widget"};g.V(MY,g.D);g.y=MY.prototype;g.y.addCueRange=function(S,b,C,z,U){S=new g.aw(S,b,{id:C,namespace:"annotations_module"});z&&this.TE.set(S,z);U&&this.GE.set(S,U);this.context.V.El([S],1)};
g.y.Hf=function(){this.context.K.subscribe("resize",this.zY,this)};
g.y.UB=function(){return this.element};
g.y.PW=function(S,b,C,z,U,a){if(this.MH)return!1;a&&(a.stopPropagation(),a.preventDefault());this.navigate(S,C,z,U);return!1};
g.y.show=function(){};
g.y.hide=function(){};
g.y.destroy=function(){g.b1(this.UB())};
g.y.zY=function(){};
g.y.navigate=function(S,b,C,z){var U=this,a=Dl(S);if(a){var J=pn6(a,S.target),H=function(){S.J&&U.context.V.pauseVideo();var B=U.context.videoData.XR||!1,x=g.$q(a||"");B&&x&&(x.v||x.list)?U.context.V.R5(x.v,b,x.list,!1):g.YV(a||"",J==="current"?"_top":void 0,b)};
J==="new"&&(H(),H=null);zo(this.context.logger,C,H,z);dGx(a)||(C=g.fV(),z=b.itct,C&&z&&g.aI(C,g.uu(z)))}};
g.y.FB=function(){this.TE.clear();this.GE.clear();g.D.prototype.FB.call(this)};
g.y.createElement=function(S){S=new g.Z(S);g.n(this,S);return S.element};g.V(Tu1,MY);g.y=Tu1.prototype;g.y.Eb=function(){this.kQ&&w4(this,this.kQ)};
g.y.isAvailable=function(){var S;if(S=!!this.cards.length)(S=this.V.getRootNode())?(S=g.hi(S),S=173<S.width&&173<S.height):S=!1;return S};
g.y.zY=function(){var S=this.isAvailable();g.IE(this.UB(),S);g.yS(this.context.V.getRootNode(),g.SV.IV_DRAWER_ENABLED,S);uE(this.V)};
g.y.destroy=function(){this.V.Xs(!1);try{this.V.getRootNode().removeChild(this.C)}catch(S){}g.aj(this.YQ);g.WA(this.De);this.Ri&&this.Ri.dispose();this.D&&this.D.dispose();MY.prototype.destroy.call(this)};
g.y.E5=function(){var S=this;this.context.J.listen(g.gq("iv-drawer-close-button",this.C),"click",this.KK,this);this.context.J.listen(this.K,"touchend",function(){S.hB.start()});
this.context.J.listen(this.K,"scroll",this.mf,this);this.context.K.subscribe("onHideControls",function(){S.UG=!0});
this.context.K.subscribe("onShowControls",function(){S.UG=!1});
this.context.K.subscribe("onVideoAreaChange",function(){S.UG=g.$g(S.V.getRootNode(),"ytp-autohide")});
this.YQ.push(g.UG("iv-button-shown",this.ojG,this));this.YQ.push(g.UG("iv-button-hidden",this.ImH,this));G21(this)};
g.y.findLastIndex=function(S){if(this.cards.length===0)return 0;var b=g.xL(this.cards,function(C){return S.xr.startMs>C.xr.startMs||S.xr.startMs===C.xr.startMs&&S.xr.timestamp>=C.xr.timestamp?!0:!1});
return b===-1?0:b+1};
g.y.KK=function(){if(this.Y){zo(this.context.logger,b8(this).R3.close);var S=g.fV();S&&this.T&&g.aI(S,this.T);IY(this)}};
g.y.mf=function(){g.yS(this.C,"iv-drawer-scrolled",this.K.scrollTop>0)};
g.y.ojG=function(){var S=g.fV(),b=b8(this);b=b?b.Ey:this.Ey;S&&b&&g.$5(S,[b])};
g.y.ImH=function(){var S=g.fV(),b=b8(this);b=b?b.Ey:this.Ey;S&&b&&g.Un(S,[b])};
g.y.aP=function(){var S=b8(this);zo(this.context.logger,S.R3.q5);var b=g.fV();if(b&&S)if(this.V.L("web_infocards_teaser_show_logging_fix")){var C=[];S.h7&&C.push(S.h7);S.Ey&&C.push(S.Ey);C.length>0&&g.$5(b,C)}else g.$5(b,[S.h7,S.Ey])};
g.y.h6_=function(){var S=g.fV(),b=b8(this);S&&b&&g.Un(S,[b.h7])};
g.y.Gt=function(S){var b=b8(this),C=g.fV();this.J?S?(S=this.context.logger,zo(S,b.R3.K2),S.V.sendVideoStatsEngageEvent(4,void 0),C&&b.h7&&g.aI(C,b.h7)):(S=this.context.logger,zo(S,b.R3.K2),S.V.sendVideoStatsEngageEvent(4,void 0),C&&b.Ey&&g.aI(C,b.Ey)):(S=this.context.logger,zo(S,b.R3.K2),S.V.sendVideoStatsEngageEvent(4,void 0),C&&this.Ey&&g.aI(C,this.Ey))};g.V(Cn,MY);Cn.prototype.Hf=function(){MY.prototype.Hf.call(this);Xn5(this)};
Cn.prototype.show=function(){MY.prototype.show.call(this);var S=g.fV(),b=this.annotation.data;S&&b&&(b=b.session_data)&&g.$5(S,[g.uu(b.itct)])};
Cn.prototype.hide=function(){MY.prototype.hide.call(this);var S=g.fV(),b=this.annotation.data;S&&b&&(b=b.session_data)&&g.Un(S,[g.uu(b.itct)])};g.V(i8,Cn);
i8.prototype.show=function(){if(!this.isActive){Cn.prototype.show.call(this);if(!this.T){g.Up(this.UB(),"iv-branding");var S=this.annotation.data;this.K=this.createElement({U:"img",i_:["branding-img","iv-click-target"],Z:{"aria-label":"Channel watermark",src:S.image_url,width:S.image_width,height:S.image_height}});g.IE(this.K,!1);var b=this.createElement({U:"button",i_:["branding-img-container","ytp-button"]});b.appendChild(this.K);this.UB().appendChild(b);var C=this.annotation.Hs();C&&r4(this,b,
C,this.annotation.id,S.session_data);this.context.V.L("disable_branding_context")||KV2(this,S);this.T=!0}g.IE(this.UB(),!0);this.isActive=!0;if(this.K){try{OI2(this,this.K)}catch(z){}g.Up(this.context.V.getRootNode(),"ytp-branding-shown");this.context.V.getRootNode().style.setProperty("--branding-image-width",this.K.getAttribute("width")+"px")}}};
i8.prototype.hide=function(){this.isActive&&(Cn.prototype.hide.call(this),g.IE(this.UB(),!1),this.isActive=!1,g.o9(this.context.V.getRootNode(),"ytp-branding-shown"))};
i8.prototype.destroy=function(){this.J&&(this.J.dispose(),this.J=null);g.o9(this.context.V.getRootNode(),"ytp-branding-shown");Cn.prototype.destroy.call(this)};g.V(cSL,Cn);g.y=cSL.prototype;g.y.show=function(){this.isActive||(Cn.prototype.show.call(this),this.j||(Nu5(this),this.j=!0),g.IE(this.UB(),!0),g.AB(function(){g.o9(this.UB(),"iv-promo-inactive")},100,this),this.UB().removeAttribute("aria-hidden"),this.isActive=!0,My6(this),n1c(this),g11(this,this.B))};
g.y.hide=function(){this.isActive&&(g.Up(this.UB(),"iv-promo-inactive"),this.isActive=!1,this.UB().setAttribute("aria-hidden","true"))};
g.y.PW=function(S,b,C,z,U,a){return this.isCollapsed?!1:Cn.prototype.PW.call(this,S,b,C,z,U,a)};
g.y.sia=function(S){this.X=!0;DGk(this,500,S)};
g.y.bxh=function(){this.X=!1;Yc1(this)};
g.y.kEB=function(S){S.stopPropagation();this.hide()};
g.y.dHR=function(S){S.stopPropagation();My6(this);this.isCollapsed=!0;g.Up(this.UB(),"iv-promo-collapsed-no-delay");this.D.start()};
g.y.destroy=function(){this.D.dispose();Cn.prototype.destroy.call(this)};g.V(ZIc,g.E8);g.y=ZIc.prototype;g.y.Q0=function(S,b){if(!JOl(this.player.G().playerStyle))return null;switch(S){case "loadCustomAnnotationsXml":return(S=g.rL(b))&&qcO(this,S),!0;case "removeCustomAnnotationById":return b&&this.J&&(k2l(this.J,b),uE(this.player)),!0}return null};
g.y.getOptions=function(){return JOl(this.player.G().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.y.X1=function(){var S=this.player.G(),b=g.c(this.player.getVideoData()),C=S.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.$P(b)||this.player.isMutedByEmbedsMutedAutoplay()?!1:C===1&&!b.qR||S.BS.get(b.videoId)||g.vY(b)||g.Kw(b)?!0:!1};
g.y.HI=function(){if(this.Y){var S=this.player.OG().getVideoContentRect(!0);g.ZU(this.Y.element,S.width,S.height);g.gX(this.Y.element,S.left,S.top)}if(this.J){var b=this.player.MN();S=this.J;b=b.width;g.yS(S.C,"iv-drawer-small",b<=426);g.yS(S.C,"iv-drawer-big",b>=1280)}};
g.y.tM=function(S){IML(this,S.state);g.h(S.state,2)&&(this.ri()&&this.gR()&&this.player.getPresentingPlayerType()!==2&&this.GZ(!1),this.Xs(!1))};
g.y.load=function(){function S(J){var H=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===H&&b.player.getVideoData().videoId===z&&(J=g.E4(J)&&J.responseXML?J.responseXML:null)&&(qcO(b,J),g.Up(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.E8.prototype.load.call(this);IML(this,this.player.getPlayerStateObject());this.loadNumber++;var C=g.c(this.player.getVideoData()),z=C.videoId;g.C5()&&(S=SiX(this,S));var U={format:"XML",onFinish:S,onError:function(){b.D=null},
urlParams:{}};C.isPharma&&(U.urlParams.pharma="1");U.method="POST";U.withCredentials=!0;var a=this.player.G().BS.get(z);a&&bD5(U,a);a=a&&(a.Yt||a.B9);if(!C.Do||a)C.PS?wnL(this,C.PS,U):(this.T=function(){if(!b.X)b.onVideoDataChange(U);var J=g.c(b.player.getVideoData());(J==null?0:g.A9(J))&&!b.YQ&&$l2(b,J)},this.player.addEventListener("videodatachange",this.T));
g.c6(this.player,this.Y.element,4);this.HI();(a=g.vY(C))&&zj1(this,a);(a=g.Kw(C))&&a.featuredChannel&&oNU(this,a.featuredChannel,a.annotationId||"branding",C.videoId||null,C.eventId||null);this.AO=g.gq("ytp-cards-button",this.player.getRootNode());g.A9(C)&&$l2(this,C)};
g.y.onVideoDataChange=function(S){var b=g.c(this.player.getVideoData());b.PS&&wnL(this,b.PS,S)};
g.y.unload=function(){this.player.pR("annotations_module");for(var S=g.t(Object.keys(this.B)),b=S.next();!b.done;b=S.next())this.B[b.value].destroy();this.j=null;this.J&&(this.J.destroy(),this.J=null,uE(this.player));this.X=!1;this.D&&(this.D.abort(),this.D=null);this.YQ=!1;this.B={};this.K.hide();g.E8.prototype.unload.call(this);this.Y.detach();this.T&&(this.player.removeEventListener("videodatachange",this.T),this.T=null)};
g.y.Yc=function(S){S===this.player.getVideoData().videoId&&(this.loaded?Cf1(this):this.load())};
g.y.ri=function(){var S;return((S=this.J)==null?void 0:S.isAvailable())||this.YQ};
g.y.gR=function(){return!!this.J&&this.J.Y};
g.y.GZ=function(S,b,C){b=b===void 0?!1:b;this.ri();this.J&&(S?C?hP(this.J,C,b):hP(this.J,"YOUTUBE_DRAWER_AUTO_OPEN",b):IY(this.J))};
g.y.Xs=function(S,b){this.player.publish(S?"cardsteasershow":"cardsteaserhide",b)};
g.y.FB=function(){this.player.G().BS.unsubscribe("vast_info_card_add",this.Yc,this);g.o9(this.player.getRootNode(),g.SV.IV_DRAWER_OPEN);for(var S=this.kQ,b=g.QA,C=0,z=S.length;C<z;C++)b.pU(S[C]);this.kQ.length=0;g.E8.prototype.FB.call(this)};
g.y.createElement=function(S){S=new g.Z(S);g.n(this,S);return S.element};g.x4("annotations_module",ZIc);g.x4("creatorendscreen",nzK);})(_yt_player);
